"""article_protected

Revision ID: 0060b4662706
Revises: 827e2c0ad4cb
Create Date: 2018-08-10 16:47:06.967282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0060b4662706'
down_revision = '827e2c0ad4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('protected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'protected')
    # ### end Alembic commands ###
