"""unique

Revision ID: 2e2326d0de84
Revises: aedfba78f23d
Create Date: 2018-08-14 14:41:27.763949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2326d0de84'
down_revision = 'aedfba78f23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_tag_mapping', 'article_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('article_tag_mapping', 'tag_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_unique_constraint('article_tag_unique', 'article_tag_mapping', ['article_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_tag_unique', 'article_tag_mapping', type_='unique')
    op.alter_column('article_tag_mapping', 'tag_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('article_tag_mapping', 'article_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
