"""add_timestamp

Revision ID: 827e2c0ad4cb
Revises: 85aaf0471fe4
Create Date: 2018-08-05 14:56:08.338176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827e2c0ad4cb'
down_revision = '85aaf0471fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
