"""user_timestamp

Revision ID: 98dba0616cf4
Revises: 2fe02ad5f190
Create Date: 2018-07-31 09:55:54.095935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dba0616cf4'
down_revision = '2fe02ad5f190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('federated_users', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('federated_users', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('local_users', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('local_users', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_users', 'updated_at')
    op.drop_column('local_users', 'created_at')
    op.drop_column('federated_users', 'updated_at')
    op.drop_column('federated_users', 'created_at')
    # ### end Alembic commands ###
